# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 936df4acd05b70534703b096d33fab102089ba0bef191687fb06ce845e2d61c0b82e99a55c3b02afdbc1ac64362865111d502afc4653d32177c4bd0e64cb58e5

test:
  secret_key_base: a1e644df74ff413fb66607102b3823a9f27dceca9785d3fd31f5be7e5c67302a143c13908346fd7790f635af8dd10b85b4fa9e566d585bd7791551042b644036

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
